name: 🌐 Web Builds
on:
  workflow_call:
    inputs:
      wasm64:
        type: boolean
        default: false
      wasm32:
        type: boolean
        default: false
  workflow_dispatch:
    inputs:
      wasm64:
        description: Build the threaded wasm64 template
        type: boolean
        default: true
      wasm32:
        description: Build the non-threaded wasm32 template
        type: boolean
        default: false

# Global Settings
env:
  SCONS_FLAGS: >-
    dev_mode=yes
    debug_symbols=no
    use_closure_compiler=yes
  EM_VERSION: 4.0.11

jobs:
  web-template:
    if: inputs.wasm64 || inputs.wasm32
    runs-on: ubuntu-24.04
    name: Template (${{ matrix.arch }})
    timeout-minutes: 60
    strategy:
      fail-fast: false
      matrix:
        arch: ${{ fromJSON(inputs.wasm64 && inputs.wasm32 && '["wasm64","wasm32"]' || inputs.wasm64 && '["wasm64"]' || '["wasm32"]') }}

    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          submodules: recursive

      - name: Set up Emscripten latest
        uses: emscripten-core/setup-emsdk@v16
        with:
          version: ${{ env.EM_VERSION }}
          no-cache: true

      - name: Verify Emscripten setup
        run: |
          emcc -v

      - name: Restore Godot build cache
        uses: ./.github/actions/godot-cache-restore
        with:
          cache-name: ${{ matrix.arch == 'wasm64' && 'web-template' || 'web-nothreads-template' }}
        continue-on-error: true

      - name: Setup Python and SCons
        uses: ./.github/actions/godot-deps

      - name: Compilation
        uses: ./.github/actions/godot-build
        with:
          scons-flags: ${{ env.SCONS_FLAGS }} threads=${{ matrix.arch == 'wasm64' && 'yes' || 'no' }} arch=${{ matrix.arch }}
          platform: web
          target: template_release

      - name: Save Godot build cache
        uses: ./.github/actions/godot-cache-save
        with:
          cache-name: ${{ matrix.arch == 'wasm64' && 'web-template' || 'web-nothreads-template' }}
        continue-on-error: true

      - name: Upload artifact
        uses: ./.github/actions/upload-artifact
        with:
          name: ${{ matrix.arch == 'wasm64' && 'web-template' || 'web-nothreads-template' }}
